language: node_js
node_js:
- 8
cache:
  directories:
  - node_modules
script:
- npm run build
- npm test -- --coverage --coverageReporters=text-lcov | ./node_modules/coveralls/bin/coveralls.js
- npm run deploy-storybook -- --ci
deploy:
  provider: heroku
  app: create-react-app-redux-boilerplate-app
  api_key:
    secure: IK54wgPHuybGHsQgdfoTnQiztB8onV+cLU9dXQnoVH1X9LvMIlrCIdH811WKd/DjTxtJEzmydIYzh+pQHKE5gXnRT0xsTEuacaifH2vLCi2VtvEcEl0X8/Sh93cLWnDdWfbuFmlAyVT4gjO6ifDhqVIqiEb9Io79T5HgsdeLfwemiEs3rYKE1vLPhVuxJWtGC5w1konWy2p03eU4WSOcSGh2N43utCVBZY5gs35NTf4CN73lgciZh3e/FF4PU2pnwzLPcZLK6RPKnNueCVCjXo/OQjRjj8hmFjK5HdoRv1gyo8c9v8MqhNz0DEBg2J/Vw4Hse1aez5F2WsXZHOnNuEFgcbb6ZW90n5u72vz63EgqDP6mEtzPOw/QvVVDbA+x7etP/niOLVmrVI24vSYzyekwELk6lOJ1FR+0cBLjrDMml151pR6rgB7VVoGs/neB1Hp5ND9sum0WAKZ3ykX1gigjTfdEZ4U5S+xYlAoyIBwj8Dw/hMq9PtdzOQbkKMtIFQ+Jio+c3+ZBwGjoFnz8jKBNg4W+I5yTPVNS86DkYusU2Og16JU+/dUa6wZNo4bn4uV3b5kHIYhq1fS344VDMln/eKRo77BeVV6pB/tiDDzV/G2hQAt11j720pmCEOm7A2L5xtB307qilfUzyI+zr32GzHTdfv2s7QKHGfcgIcg=
